
header = """
/* wrapper Header */
#ifdef __cplusplus
extern "C" {
#endif
"""
trailer = """
#ifdef __cplusplus
} /* extern "C" */
#endif
"""

include_guard = "wrapper_H"
include_version = true
language = "C"

[parse]
parse_deps = true
include = []

[enum]
prefix_with_name = true